-- 1st Stage
-- CREATE DATABASE db_name;
CREATE DATABASE db_campus;
-- CHECKING DATABASE IS EXIST
SHOW DATABASES;
-- ACCESS & USING DATABASE IS EXIST
USE db_campus; 
-- CREATING TABLE INTO DATABASE
CREATE TABLE tbl_student (
id_student INT(11) PRIMARY KEY,
student_name VARCHAR(50),
address TEXT,
email TEXT,
phone TEXT
);
-- CHECKING TABLE
SHOW TABLES;